import type { Product } from "./types"

export const products: Product[] = [
  // Adderall Products
  {
    id: "adderall-5mg",
    name: "Adderall 5mg",
    description: "Adderall 5mg tablets for the treatment of ADHD and narcolepsy.",
    price: 308,
    image: "/images/Adderall/Adderall5mg.jpg",
    images: ["/images/Adderall/Adderall5mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "adderall-7-5mg",
    name: "Adderall 7.5mg",
    description: "Adderall 7.5mg tablets for the treatment of ADHD and narcolepsy.",
    price: 338,
    image: "/images/Adderall/adderall7_5mg-300x225.jpg",
    images: ["/images/Adderall/adderall7_5mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "adderall-10mg",
    name: "Adderall 10mg",
    description: "Adderall 10mg tablets for the treatment of ADHD and narcolepsy.",
    price: 338,
    image: "/images/Adderall/addreall10mg.jpg",
    images: ["/images/Adderall/addreall10mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "adderall-12-5mg",
    name: "Adderall 12.5mg",
    description: "Adderall 12.5mg tablets for the treatment of ADHD and narcolepsy.",
    price: 368,
    image: "/images/Adderall/adderall12_5mg-3-300x225.jpg",
    images: ["/images/Adderall/adderall12_5mg-3-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "adderall-15mg",
    name: "Adderall 15mg",
    description: "Adderall 15mg tablets for the treatment of ADHD and narcolepsy.",
    price: 358,
    image: "/images/Adderall/adderall15mg-300x225.jpg",
    images: ["/images/Adderall/adderall15mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "adderall-20mg",
    name: "Adderall 20mg",
    description: "Adderall 20mg tablets for the treatment of ADHD and narcolepsy.",
    price: 368,
    image: "/images/Adderall/Adderall20mg.jpg",
    images: ["/images/Adderall/Adderall20mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: "adderall-30mg",
    name: "Adderall 30mg",
    description: "Adderall 30mg tablets for the treatment of ADHD and narcolepsy.",
    price: 438,
    image: "/images/Adderall/addrea30mg.jpg",
    images: ["/images/Adderall/addrea30mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: "adderall-xr-5mg",
    name: "Adderall XR 5mg",
    description: "Adderall XR 5mg extended-release capsules for the treatment of ADHD and narcolepsy.",
    price: 283,
    image: "/images/Adderall/Adderallxr5mg-2-300x225.jpg",
    images: ["/images/Adderall/Adderallxr5mg-2-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "adderall-xr-10mg",
    name: "Adderall XR 10mg",
    description: "Adderall XR 10mg extended-release capsules for the treatment of ADHD and narcolepsy.",
    price: 338,
    image: "/images/Adderall/AdderallXR10mg-300x225.jpg",
    images: ["/images/Adderall/AdderallXR10mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "adderall-xr-15mg",
    name: "Adderall XR 15mg",
    description: "Adderall XR 15mg extended-release capsules for the treatment of ADHD and narcolepsy.",
    price: 328,
    image: "/images/Adderall/AdderallXR15mg-300x225.jpg",
    images: ["/images/Adderall/AdderallXR15mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "adderall-xr-20mg",
    name: "Adderall XR 20mg",
    description: "Adderall XR 20mg extended-release capsules for the treatment of ADHD and narcolepsy.",
    price: 338,
    image: "/images/Adderall/AdderallXR20mg-300x225.jpg",
    images: ["/images/Adderall/AdderallXR20mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "adderall-xr-25mg",
    name: "Adderall XR 25mg",
    description: "Adderall XR 25mg extended-release capsules for the treatment of ADHD and narcolepsy.",
    price: 358,
    image: "/images/Adderall/AdderallXR25mg25-300x225.jpg",
    images: ["/images/Adderall/AdderallXR25mg25-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "adderall-xr-30mg",
    name: "Adderall XR 30mg",
    description: "Adderall XR 30mg extended-release capsules for the treatment of ADHD and narcolepsy.",
    price: 368,
    image: "/images/Adderall/AdderallXR30mg-300x225.jpg",
    images: ["/images/Adderall/AdderallXR30mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adderall",
    featured: false,
    inStock: true,
    rating: 4.9,
  },

  // Adipex Products
  {
    id: "adipex-375mg",
    name: "Adipex 375mg",
    description: "Adipex 375mg tablets for weight management and obesity treatment.",
    price: 283,
    image: "/images/Adipex/ADIPEXP375.jpg",
    images: ["/images/Adipex/ADIPEXP375.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "adipex",
    featured: false,
    inStock: true,
    rating: 4.6,
  },

  // Alprazolam Products
  {
    id: "alprazolam-0-25mg",
    name: "Alprazolam 0.25mg",
    description: "Alprazolam 0.25mg tablets for anxiety and panic disorders.",
    price: 308,
    image: "/images/Alprazolam/ALPRAZOLAM0.25.jpg",
    images: ["/images/Alprazolam/ALPRAZOLAM0.25.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "alprazolam",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "alprazolam-0-5mg",
    name: "Alprazolam 0.5mg",
    description: "Alprazolam 0.5mg tablets for anxiety and panic disorders.",
    price: 308,
    image: "/images/Alprazolam/ALPRAZOLAM0.5MG.jpg",
    images: ["/images/Alprazolam/ALPRAZOLAM0.5MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "alprazolam",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "alprazolam-1mg",
    name: "Alprazolam 1mg",
    description: "Alprazolam 1mg tablets for anxiety and panic disorders.",
    price: 318,
    image: "/images/Alprazolam/ALPRAZOLAM1MG.jpg",
    images: ["/images/Alprazolam/ALPRAZOLAM1MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "alprazolam",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "alprazolam-2mg",
    name: "Alprazolam 2mg",
    description: "Alprazolam 2mg tablets for anxiety and panic disorders.",
    price: 328,
    image: "/images/Alprazolam/ALPRAZOLAM2MG.jpg",
    images: ["/images/Alprazolam/ALPRAZOLAM2MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "alprazolam",
    featured: true,
    inStock: true,
    rating: 4.9,
  },

  // Ambien Products
  {
    id: "ambien-10mg",
    name: "Ambien 10mg",
    description: "Ambien 10mg tablets for short-term treatment of insomnia.",
    price: 312,
    image: "/images/Ambien/Ambien10mg-300x225.jpg",
    images: ["/images/Ambien/Ambien10mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "ambien",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "ambien-5mg",
    name: "Ambien 5mg",
    description: "Ambien 5mg tablets for short-term treatment of insomnia.",
    price: 304,
    image: "/images/Ambien/Ambien5mg-300x225.jpg",
    images: ["/images/Ambien/Ambien5mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "ambien",
    featured: false,
    inStock: true,
    rating: 4.7,
  },

  // Ativan Products
  {
    id: "ativan-1mg",
    name: "Ativan 1mg",
    description: "Ativan 1mg tablets for anxiety, insomnia, and seizures.",
    price: 278,
    image: "/images/Ativan/ativan-1mg-300x225.jpg",
    images: ["/images/Ativan/ativan-1mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "ativan",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "ativan-2mg",
    name: "Ativan 2mg",
    description: "Ativan 2mg tablets for anxiety, insomnia, and seizures.",
    price: 298,
    image: "/images/Ativan/ativan-2mg-300x225.jpg",
    images: ["/images/Ativan/ativan-2mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "ativan",
    featured: true,
    inStock: true,
    rating: 4.8,
  },

  // Cialis Products
  {
    id: "cialis-5mg",
    name: "Cialis 5mg",
    description: "Cialis 5mg tablets for erectile dysfunction and symptoms of benign prostatic hyperplasia.",
    price: 358,
    image: "/images/Cialis/CIALIS5MG.jpg",
    images: ["/images/Cialis/CIALIS5MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "cialis",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "cialis-10mg",
    name: "Cialis 10mg",
    description: "Cialis 10mg tablets for erectile dysfunction and symptoms of benign prostatic hyperplasia.",
    price: 378,
    image: "/images/Cialis/CIALIS10MG.jpg",
    images: ["/images/Cialis/CIALIS10MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "cialis",
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: "cialis-20mg",
    name: "Cialis 20mg",
    description: "Cialis 20mg tablets for erectile dysfunction and symptoms of benign prostatic hyperplasia.",
    price: 398,
    image: "/images/Cialis/CIALIS20MG.jpg",
    images: ["/images/Cialis/CIALIS20MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "cialis",
    featured: true,
    inStock: true,
    rating: 5.0,
  },

  // Xanax Products
  {
    id: "xanax-0-5mg",
    name: "Xanax 0.5mg",
    description: "Xanax 0.5mg tablets for anxiety and panic disorders.",
    price: 328,
    image: "/images/Xanax/Xanax_5mg-300x225.jpg",
    images: ["/images/Xanax/Xanax_5mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "xanax",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "xanax-1mg",
    name: "Xanax 1mg",
    description: "Xanax 1mg tablets for anxiety and panic disorders.",
    price: 338,
    image: "/images/Xanax/Xanax1mg-300x225.jpg",
    images: ["/images/Xanax/Xanax1mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "xanax",
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: "xanax-2mg",
    name: "Xanax 2mg",
    description: "Xanax 2mg tablets for anxiety and panic disorders.",
    price: 358,
    image: "/images/Xanax/Xanax2mg-300x225.jpg",
    images: ["/images/Xanax/Xanax2mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "xanax",
    featured: true,
    inStock: true,
    rating: 5.0,
  },
  {
    id: "xanax-2-5mg",
    name: "Xanax 2.5mg",
    description: "Xanax 2.5mg tablets for anxiety and panic disorders.",
    price: 368,
    image: "/images/Xanax/Xanax_25mg-300x225.jpg",
    images: ["/images/Xanax/Xanax_25mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "xanax",
    featured: false,
    inStock: true,
    rating: 4.9,
  },
  {
    id: "blue-xanax",
    name: "Blue Xanax",
    description: "Blue Xanax tablets for anxiety and panic disorders.",
    price: 348,
    image: "/images/Xanax/blue-xanax.jpg",
    images: ["/images/Xanax/blue-xanax.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "xanax",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "yellow-xanax",
    name: "Yellow Xanax",
    description: "Yellow Xanax tablets for anxiety and panic disorders.",
    price: 358,
    image: "/images/Xanax/yellow-xanax-bar-300x225.jpg",
    images: ["/images/Xanax/yellow-xanax-bar-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "xanax",
    featured: false,
    inStock: true,
    rating: 4.8,
  },

  // Viagra Products
  {
    id: "viagra-25mg",
    name: "Viagra 25mg",
    description: "Viagra 25mg tablets for treating erectile dysfunction.",
    price: 308,
    image: "/images/Viagra/viagra25mg.jpg",
    images: ["/images/Viagra/viagra25mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "viagra",
    featured: true,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "viagra-50mg",
    name: "Viagra 50mg",
    description: "Viagra 50mg tablets for treating erectile dysfunction.",
    price: 318,
    image: "/images/Viagra/viagra50mg.jpg",
    images: ["/images/Viagra/viagra50mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "viagra",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "viagra-100mg",
    name: "Viagra 100mg",
    description: "Viagra 100mg tablets for treating erectile dysfunction.",
    price: 338,
    image: "/images/Viagra/viagra100mg.jpg",
    images: ["/images/Viagra/viagra100mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "viagra",
    featured: true,
    inStock: true,
    rating: 4.9,
  },

  // Tramadol Products
  {
    id: "tramadol-50mg",
    name: "Tramadol 50mg",
    description: "Tramadol 50mg tablets for moderate to severe pain relief.",
    price: 277,
    image: "/images/Tramadol/tramadol50_mg.jpg",
    images: ["/images/Tramadol/tramadol50_mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "tramadol",
    featured: false,
    inStock: true,
    rating: 4.6,
  },
  {
    id: "tramadol-100mg",
    name: "Tramadol 100mg",
    description: "Tramadol 100mg tablets for moderate to severe pain relief.",
    price: 297,
    image: "/images/Tramadol/tramadol100mg.jpg",
    images: ["/images/Tramadol/tramadol100mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "tramadol",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "tramadol-200mg",
    name: "Tramadol 200mg",
    description: "Tramadol 200mg tablets for moderate to severe pain relief.",
    price: 318,
    image: "/images/Tramadol/tramadol200mg-2.jpg",
    images: ["/images/Tramadol/tramadol200mg-2.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "tramadol",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "tramadol-37-5-325mg",
    name: "Tramadol 37.5/325mg",
    description: "Tramadol 37.5/325mg combination tablets for moderate to severe pain relief.",
    price: 318,
    image: "/images/Tramadol/tramadol375mg_325mg.jpg",
    images: ["/images/Tramadol/tramadol375mg_325mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "tramadol",
    featured: false,
    inStock: true,
    rating: 4.7,
  },

  // Valium Products
  {
    id: "valium-5mg",
    name: "Valium 5mg",
    description: "Valium 5mg tablets for anxiety, muscle spasms, and seizures.",
    price: 358,
    image: "/images/Valium/Valium-5mg.png",
    images: ["/images/Valium/Valium-5mg.png"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "valium",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "valium-10mg",
    name: "Valium 10mg",
    description: "Valium 10mg tablets for anxiety, muscle spasms, and seizures.",
    price: 368,
    image: "/images/Valium/Valium-10mg-1.png",
    images: ["/images/Valium/Valium-10mg-1.png"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "valium",
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  
  // Zolpidem Products
  {
    id: "zolpidem-5mg",
    name: "Zolpidem 5mg",
    description: "Zolpidem 5mg tablets for the short-term treatment of insomnia.",
    price: 334,
    image: "/images/Zolpidem/Zolpidem-5mg.png",
    images: ["/images/Zolpidem/Zolpidem-5mg.png"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "zolpidem",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "zolpidem-10mg",
    name: "Zolpidem 10mg",
    description: "Zolpidem 10mg tablets for the short-term treatment of insomnia.",
    price: 354,
    image: "/images/Zolpidem/Zolpidem-10mg.png",
    images: ["/images/Zolpidem/Zolpidem-10mg.png"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "zolpidem",
    featured: true,
    inStock: true,
    rating: 4.8,
  },

  // Hydrocodone Products
  {
    id: "hydrocodone-5-325mg",
    name: "Hydrocodone 5/325mg",
    description: "Hydrocodone 5/325mg tablets for moderate to severe pain relief.",
    price: 328,
    image: "/images/Hydrocodone/hydrocodone5.325MG.jpg",
    images: ["/images/Hydrocodone/hydrocodone5.325MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "hydrocodone",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "hydrocodone-5-500mg",
    name: "Hydrocodone 5/500mg",
    description: "Hydrocodone 5/500mg tablets for moderate to severe pain relief.",
    price: 338,
    image: "/images/Hydrocodone/Hydrocodone5.500MG.jpg",
    images: ["/images/Hydrocodone/Hydrocodone5.500MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "hydrocodone",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "hydrocodone-7-5-325mg",
    name: "Hydrocodone 7.5/325mg",
    description: "Hydrocodone 7.5/325mg tablets for moderate to severe pain relief.",
    price: 348,
    image: "/images/Hydrocodone/hydrocodone7.5.325MG.jpg",
    images: ["/images/Hydrocodone/hydrocodone7.5.325MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "hydrocodone",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "hydrocodone-7-5-500mg",
    name: "Hydrocodone 7.5/500mg",
    description: "Hydrocodone 7.5/500mg tablets for moderate to severe pain relief.",
    price: 358,
    image: "/images/Hydrocodone/hydrocodone7.5-500MG.jpg",
    images: ["/images/Hydrocodone/hydrocodone7.5-500MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "hydrocodone",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "hydrocodone-10mg",
    name: "Hydrocodone 10mg",
    description: "Hydrocodone 10mg tablets for moderate to severe pain relief.",
    price: 368,
    image: "/images/Hydrocodone/HYDROCODONE10.jpg",
    images: ["/images/Hydrocodone/HYDROCODONE10.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "hydrocodone",
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: "hydrocodone-10-325mg",
    name: "Hydrocodone 10/325mg",
    description: "Hydrocodone 10/325mg tablets for moderate to severe pain relief.",
    price: 368,
    image: "/images/Hydrocodone/hydrocodone10.325MG.jpg",
    images: ["/images/Hydrocodone/hydrocodone10.325MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "hydrocodone",
    featured: true,
    inStock: true,
    rating: 4.9,
  },

  // Oxycodone Products
  {
    id: "oxycodone-5mg",
    name: "Oxycodone 5mg",
    description: "Oxycodone 5mg tablets for moderate to severe pain relief.",
    price: 338,
    image: "/images/Oxycodone/oxycodone5mg-300x225.jpg",
    images: ["/images/Oxycodone/oxycodone5mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "oxycodone",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "oxycodone-10mg",
    name: "Oxycodone 10mg",
    description: "Oxycodone 10mg tablets for moderate to severe pain relief.",
    price: 358,
    image: "/images/Oxycodone/Oxycodone10mg-300x225.jpg",
    images: ["/images/Oxycodone/Oxycodone10mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "oxycodone",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "oxycodone-15mg",
    name: "Oxycodone 15mg",
    description: "Oxycodone 15mg tablets for moderate to severe pain relief.",
    price: 368,
    image: "/images/Oxycodone/oxycodone15mg-300x225.jpg",
    images: ["/images/Oxycodone/oxycodone15mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "oxycodone",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "oxycodone-20mg",
    name: "Oxycodone 20mg",
    description: "Oxycodone 20mg tablets for moderate to severe pain relief.",
    price: 378,
    image: "/images/Oxycodone/Oxycodone20mg-300x225.jpg",
    images: ["/images/Oxycodone/Oxycodone20mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "oxycodone",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "oxycodone-30mg",
    name: "Oxycodone 30mg",
    description: "Oxycodone 30mg tablets for moderate to severe pain relief.",
    price: 388,
    image: "/images/Oxycodone/oxycodone30mg-300x225.jpg",
    images: ["/images/Oxycodone/oxycodone30mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "oxycodone",
    featured: true,
    inStock: true,
    rating: 4.9,
  },

  // Oxycontin Products
  {
    id: "oxycontin-10mg",
    name: "Oxycontin 10mg",
    description: "Oxycontin 10mg controlled-release tablets for moderate to severe pain relief.",
    price: 358,
    image: "/images/Oxycontin/Oxycontin10mg-300x225.jpg",
    images: ["/images/Oxycontin/Oxycontin10mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "oxycontin",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "oxycontin-20mg",
    name: "Oxycontin 20mg",
    description: "Oxycontin 20mg controlled-release tablets for moderate to severe pain relief.",
    price: 378,
    image: "/images/Oxycontin/Oxycontin20mg-300x225.jpg",
    images: ["/images/Oxycontin/Oxycontin20mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "oxycontin",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "oxycontin-30mg",
    name: "Oxycontin 30mg",
    description: "Oxycontin 30mg controlled-release tablets for moderate to severe pain relief.",
    price: 398,
    image: "/images/Oxycontin/oxycontin30mg-300x225.jpg",
    images: ["/images/Oxycontin/oxycontin30mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "oxycontin",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "oxycontin-40mg",
    name: "Oxycontin 40mg",
    description: "Oxycontin 40mg controlled-release tablets for moderate to severe pain relief.",
    price: 428,
    image: "/images/Oxycontin/Oxycontin40mg-300x225.jpg",
    images: ["/images/Oxycontin/Oxycontin40mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "oxycontin",
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: "oxycontin-80mg",
    name: "Oxycontin 80mg",
    description: "Oxycontin 80mg controlled-release tablets for moderate to severe pain relief.",
    price: 468,
    image: "/images/Oxycontin/oxycontin80oc.jpg",
    images: ["/images/Oxycontin/oxycontin80oc.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "oxycontin",
    featured: true,
    inStock: true,
    rating: 5.0,
  },

  // Methadone Products
  {
    id: "methadone-5mg",
    name: "Methadone 5mg",
    description: "Methadone 5mg tablets for severe pain relief and opioid dependence treatment.",
    price: 318,
    image: "/images/Methadone/methadone5mg.jpg",
    images: ["/images/Methadone/methadone5mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "methadone",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "methadone-10mg",
    name: "Methadone 10mg",
    description: "Methadone 10mg tablets for severe pain relief and opioid dependence treatment.",
    price: 338,
    image: "/images/Methadone/methadone10mg.jpg",
    images: ["/images/Methadone/methadone10mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "methadone",
    featured: true,
    inStock: true,
    rating: 4.8,
  },

  // Percocet Products
  {
    id: "percocet-2-5-325mg",
    name: "Percocet 2.5/325mg",
    description: "Percocet 2.5/325mg tablets containing oxycodone and acetaminophen for moderate to severe pain relief.",
    price: 328,
    image: "/images/Percocet/Percocet2.5_325mg-300x225.jpg",
    images: ["/images/Percocet/Percocet2.5_325mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "percocet",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "percocet-5-325mg",
    name: "Percocet 5/325mg",
    description: "Percocet 5/325mg tablets containing oxycodone and acetaminophen for moderate to severe pain relief.",
    price: 338,
    image: "/images/Percocet/Percocet5_325mg-300x225.jpg",
    images: ["/images/Percocet/Percocet5_325mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "percocet",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "percocet-7-5-325mg",
    name: "Percocet 7.5/325mg",
    description: "Percocet 7.5/325mg tablets containing oxycodone and acetaminophen for moderate to severe pain relief.",
    price: 348,
    image: "/images/Percocet/Percocet7.5_325mg-300x225.jpg",
    images: ["/images/Percocet/Percocet7.5_325mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "percocet",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "percocet-10-325mg",
    name: "Percocet 10/325mg",
    description: "Percocet 10/325mg tablets containing oxycodone and acetaminophen for moderate to severe pain relief.",
    price: 358,
    image: "/images/Percocet/Percocet10_325mg-300x225.jpg",
    images: ["/images/Percocet/Percocet10_325mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "percocet",
    featured: true,
    inStock: true,
    rating: 4.9,
  },

  // Norco Products
  {
    id: "norco-5-325mg",
    name: "Norco 5/325mg",
    description: "Norco 5/325mg tablets containing hydrocodone and acetaminophen for moderate to severe pain relief.",
    price: 318,
    image: "/images/Norco/Norco5_325mg-300x225.jpg",
    images: ["/images/Norco/Norco5_325mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "norco",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "norco-7-5-325mg",
    name: "Norco 7.5/325mg",
    description: "Norco 7.5/325mg tablets containing hydrocodone and acetaminophen for moderate to severe pain relief.",
    price: 328,
    image: "/images/Norco/Norco-7.5_325mg-1-1-300x225.jpg",
    images: ["/images/Norco/Norco-7.5_325mg-1-1-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "norco",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "norco-10-325mg",
    name: "Norco 10/325mg",
    description: "Norco 10/325mg tablets containing hydrocodone and acetaminophen for moderate to severe pain relief.",
    price: 338,
    image: "/images/Norco/norco10_325mg-265x225.jpg",
    images: ["/images/Norco/norco10_325mg-265x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "norco",
    featured: true,
    inStock: true,
    rating: 4.9,
  },

  // Vicodin Products
  {
    id: "vicodin-5-500mg",
    name: "Vicodin 5/500mg",
    description: "Vicodin 5/500mg tablets containing hydrocodone and acetaminophen for moderate to severe pain relief.",
    price: 328,
    image: "/images/Vicodin/VICODIN5_500MG.jpg",
    images: ["/images/Vicodin/VICODIN5_500MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "vicodin",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "vicodin-7-5-750mg",
    name: "Vicodin 7.5/750mg",
    description: "Vicodin 7.5/750mg tablets containing hydrocodone and acetaminophen for moderate to severe pain relief.",
    price: 348,
    image: "/images/Vicodin/VICODIN75750.jpg",
    images: ["/images/Vicodin/VICODIN75750.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "vicodin",
    featured: true,
    inStock: true,
    rating: 4.9,
  },

  // Lortab Products
  {
    id: "lortab-5-325mg",
    name: "Lortab 5/325mg",
    description: "Lortab 5/325mg tablets containing hydrocodone and acetaminophen for moderate to severe pain relief.",
    price: 318,
    image: "/images/Lortab/lortab5_325mg.jpg",
    images: ["/images/Lortab/lortab5_325mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "lortab",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "lortab-5-500mg",
    name: "Lortab 5/500mg",
    description: "Lortab 5/500mg tablets containing hydrocodone and acetaminophen for moderate to severe pain relief.",
    price: 328,
    image: "/images/Lortab/Lortab5_500mg-300x225.jpg",
    images: ["/images/Lortab/Lortab5_500mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "lortab",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "lortab-7-5-325mg",
    name: "Lortab 7.5/325mg",
    description: "Lortab 7.5/325mg tablets containing hydrocodone and acetaminophen for moderate to severe pain relief.",
    price: 338,
    image: "/images/Lortab/lortab_7_5_325.jpg",
    images: ["/images/Lortab/lortab_7_5_325.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "lortab",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "lortab-7-5-500mg",
    name: "Lortab 7.5/500mg",
    description: "Lortab 7.5/500mg tablets containing hydrocodone and acetaminophen for moderate to severe pain relief.",
    price: 348,
    image: "/images/Lortab/Lortab75_500mg-300x225.jpg",
    images: ["/images/Lortab/Lortab75_500mg-300x225.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "lortab",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "lortab-10-325mg",
    name: "Lortab 10/325mg",
    description: "Lortab 10/325mg tablets containing hydrocodone and acetaminophen for moderate to severe pain relief.",
    price: 358,
    image: "/images/Lortab/lortab10_325mg.jpg",
    images: ["/images/Lortab/lortab10_325mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "lortab",
    featured: true,
    inStock: true,
    rating: 4.9,
  },

  // Roxicodone Products
  {
    id: "roxicodone-5mg",
    name: "Roxicodone 5mg",
    description: "Roxicodone 5mg tablets for moderate to severe pain relief.",
    price: 338,
    image: "/images/Roxicodone/roxicodone5MG.jpg",
    images: ["/images/Roxicodone/roxicodone5MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "roxicodone",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "roxicodone-15mg",
    name: "Roxicodone 15mg",
    description: "Roxicodone 15mg tablets for moderate to severe pain relief.",
    price: 358,
    image: "/images/Roxicodone/roxicodone15MG.jpg",
    images: ["/images/Roxicodone/roxicodone15MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "roxicodone",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "roxicodone-30mg",
    name: "Roxicodone 30mg",
    description: "Roxicodone 30mg tablets for moderate to severe pain relief.",
    price: 378,
    image: "/images/Roxicodone/roxicodone30MG.jpg",
    images: ["/images/Roxicodone/roxicodone30MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "roxicodone",
    featured: true,
    inStock: true,
    rating: 4.9,
  },

  // Opana Products
  {
    id: "opana-5mg",
    name: "Opana 5mg",
    description: "Opana 5mg tablets containing oxymorphone for moderate to severe pain relief.",
    price: 338,
    image: "/images/Opana/opana5mger.jpg",
    images: ["/images/Opana/opana5mger.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "opana",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "opana-10mg",
    name: "Opana 10mg",
    description: "Opana 10mg tablets containing oxymorphone for moderate to severe pain relief.",
    price: 358,
    image: "/images/Opana/opana10_mg.jpg",
    images: ["/images/Opana/opana10_mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "opana",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "opana-15mg",
    name: "Opana 15mg",
    description: "Opana 15mg tablets containing oxymorphone for moderate to severe pain relief.",
    price: 378,
    image: "/images/Opana/opana15mg.jpg",
    images: ["/images/Opana/opana15mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "opana",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "opana-20mg",
    name: "Opana 20mg",
    description: "Opana 20mg tablets containing oxymorphone for moderate to severe pain relief.",
    price: 398,
    image: "/images/Opana/opana20mg.jpg",
    images: ["/images/Opana/opana20mg.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "opana",
    featured: true,
    inStock: true,
    rating: 4.9,
  },

  // Suboxone Products
  {
    id: "suboxone-2mg",
    name: "Suboxone 2mg",
    description: "Suboxone 2mg sublingual film containing buprenorphine and naloxone for opioid dependence treatment.",
    price: 328,
    image: "/images/Suboxone/SUBOXONEN2MG.jpg",
    images: ["/images/Suboxone/SUBOXONEN2MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "suboxone",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "suboxone-8mg",
    name: "Suboxone 8mg",
    description: "Suboxone 8mg sublingual film containing buprenorphine and naloxone for opioid dependence treatment.",
    price: 348,
    image: "/images/Suboxone/SUBOXONEN8MG.jpg",
    images: ["/images/Suboxone/SUBOXONEN8MG.jpg"],
    variations: ["30 pills", "60 pills", "90 pills"],
    category: "suboxone",
    featured: true,
    inStock: true,
    rating: 4.8,
  },

  // Existing ED Products
  {
    id: "sildenafil-50",
    name: "Sildenafil 50mg",
    description: "Popular option for treating ED. Delivers proven results and improved intimacy.",
    price: 100,
    image: "/images/sildenafil-50.webp",
    images: ["/images/sildenafil-50.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "sildenafil",
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: "sildenafil-100",
    name: "Sildenafil 100mg",
    description: "Maximum strength for those needing stronger support. Trusted by millions worldwide.",
    price: 100,
    image: "/images/sildenafil-100.webp",
    images: ["/images/sildenafil-100.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "sildenafil",
    featured: true,
    inStock: true,
    rating: 5.0,
  },
  {
    id: "sildenafil-120",
    name: "Sildenafil 120mg",
    description: "Extra strong formula for optimal performance. Take your confidence to the next level.",
    price: 100,
    image: "/images/sildenafil-120.webp",
    images: ["/images/sildenafil-120.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "sildenafil",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
  {
    id: "sildenafil-150",
    name: "Sildenafil 150mg",
    description: "High dose for advanced support. Ideal for those seeking potent, lasting results.",
    price: 100,
    image: "/images/sildenafil-150.webp",
    images: ["/images/sildenafil-150.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "sildenafil",
    featured: false,
    inStock: true,
    rating: 4.9,
  },
  {
    id: "sildenafil-200",
    name: "Sildenafil 200mg",
    description: "Our strongest Sildenafil. For those who need reliable, top-tier performance.",
    price: 100,
    image: "/images/sildenafil-200.webp",
    images: ["/images/sildenafil-200.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "sildenafil",
    featured: false,
    inStock: true,
    rating: 4.8,
  },

  // TADALAFIL
  {
    id: "calis-20",
    name: "Tadalafil 20mg",
    description: "Enjoy up to 36 hours of effectiveness with our most popular daily option.",
    price: 100,
    image: "/images/calis-20.webp",
    images: ["/images/calis-20.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "tadalafil",
    featured: true,
    inStock: true,
    rating: 4.9,
  },
  {
    id: "calis-40",
    name: "Tadalafil 40mg",
    description: "Double the strength for men who want even more reliable results.",
    price: 100,
    image: "/images/calis-40.webp",
    images: ["/images/calis-40.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "tadalafil",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "calis-60",
    name: "Tadalafil 60mg",
    description: "Strong support and longer-lasting effects for complete peace of mind.",
    price: 100,
    image: "/images/calis-60.webp",
    images: ["/images/calis-60.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "tadalafil",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "calis-80",
    name: "Tadalafil 80mg",
    description: "Our highest strength for enhanced performance and lasting confidence.",
    price: 100,
    image: "/images/calis-80.webp",
    images: ["/images/calis-80.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "tadalafil",
    featured: false,
    inStock: true,
    rating: 4.8,
  },

  // VARDENAFIL
  {
    id: "lavitra-20",
    name: "Vardenafil 20mg",
    description: "Fast-acting ED solution for on-demand results and spontaneous moments.",
    price: 100,
    image: "/images/lavitra-20.webp",
    images: ["/images/lavitra-20.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "vardenafil",
    featured: true,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "lavitra-40",
    name: "Vardenafil 40mg",
    description: "Increased potency for those needing a stronger ED solution.",
    price: 100,
    image: "/images/lavitra-40.webp",
    images: ["/images/lavitra-40.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "vardenafil",
    featured: false,
    inStock: true,
    rating: 4.8,
  },
  {
    id: "lavitra-60",
    name: "Vardenafil 60mg",
    description: "Extra-strength dose for reliable, powerful performance when it matters.",
    price: 100,
    image: "/images/lavitra-60.webp",
    images: ["/images/lavitra-60.webp"],
    variations: ["100 pills", "200 pills", "300 pills", "500 pills"],
    category: "vardenafil",
    featured: false,
    inStock: true,
    rating: 4.7,
  },
]


export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((product) => product.category === category)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.featured)
}

export function getRelatedProducts(id: string): Product[] {
  const product = products.find((product) => product.id === id)
  if (!product) return []

  return products.filter((p) => p.category === product.category && p.id !== id)
}
